### PR TITLE
Add header dependencies to Makefiles

### PR DESCRIPTION
**Pull request by Jcw87**
For smarter rebuilds.

This needs testing in more environments, like Linux and WSL

### CODE REVIEW

**Comment by jdflyer** [comment]
I can confirm this works on linux. However, I have some concerns about build time. A Full build on my system on the current repository takes 6 seconds less than this build. Additionally, make on this PR takes about twice the time to process files before execution than the current repository (this time a makes a huge difference when using diff.py). Is there any way to make including dependency files optional?

**Comment by Jcw87** [comment]
I've added a `DISABLE_DEPS` makefile variable that will ignore all extra processing related to the header dependencies if it is set to anything. This includes the compiler generating the `.d` file, the post-processing step to fix the path separators, and the include statement that uses the `.d` files. `diff.py` still needs to be changed to use it.

**Comment by jdflyer** [comment]
Looks good! If you add DISABLE_DEPS=1 to the makeflags in diff_settings.py it's good with me!

**Review by jdflyer — APPROVED** [review]

**Comment by Jcw87** [comment]
I got so focused on handling the 800 or so makefiles for the libraries and rels that I forgot about main.dol. Should probably give that a quick review before merging

**Pull request merged**
