### PR TITLE
Automated setup implementation

### PR DESCRIPTION
**Pull request by DRK-512**
I modified the Makefile to automate some steps in the project setup

### CODE REVIEW

**Comment by jdflyer** [comment]
We should probably move this to the setup function in tools/tp.py to keep the setup script all in one place

**Comment by DRK-512** [comment]
@jdflyer I will undo my commit, and have it as part of the tp setup python script

**Review by Pheenoh — APPROVED** [review]

**Comment by DRK-512** [comment]
It looks as if this as been approved, and all merge conflicts have been resolved

**Comment by Pheenoh** [comment]
I added requests to the container image, undo your last commit and we can merge this in

**Pull request merged**
