### PR TITLE
Add frank.py

### PR DESCRIPTION
**Pull request by jdflyer**
This adds frank.py (from the pikmin 2 decomp) which fixes epilogue issues in the 1.2.5 compiler that the os libs use.

### CODE REVIEW

**Comment by TakaRikka** [comment]
is this using the 1.2.5e compiler or just base 1.2.5?

**Comment by jdflyer** [comment]
It's just frank.py on object files compiled with base 1.2.5

**Comment by TakaRikka** [comment]
ah okay, wasn't sure if it was required or not. seems fine then

**Comment by jdflyer** [comment]
Let me see if I can get rid of any more diffs by using 1.2.5e

**Comment by jdflyer** [comment]
It seems like 1.2.5e needs some setup to compile files so I guess we can just leave it on base 1.2.5 for now

**Review by TakaRikka — APPROVED** [review]

**Pull request merged**
