### PR TITLE
d_a_tag_river_back OK

### PR DESCRIPTION
**Pull request by hatal175**
@hev7 
Thought you might be interested to see what the issues were.

1. daTagRiverBack_c::create - misplaced if, needed l_arcName instead of the explicit string
2. daTagRiverBack_c::event_proc_call - the init data was in [unknown_translation_unit_bss.cpp. Just needed to delete that and it matched.
3. daTagRiverBack_c::demoProc - matched as is.

## CC0 License Agreement

- [x] I agree to the terms of the CC0 License.

### CODE REVIEW

**Comment by hev7** [comment]
> @hev7 Thought you might be interested to see what the issues were.
> 
>     1. daTagRiverBack_c::create - misplaced if, needed l_arcName instead of the explicit string
> 
>     2. daTagRiverBack_c::event_proc_call - the init data was in [unknown_translation_unit_bss.cpp. Just needed to delete that and it matched.
> 
>     3. daTagRiverBack_c::demoProc - matched as is.
> 
> 

Ah thanks, that is good to know.

**Comment by Trueffeloot** [comment]
@hatal175 did you format the TU? I'd also remove the "forward references" and "external references" and such since the TU is finished

**Comment by hatal175** [comment]
I usually just remove the contents rather than the reference headers.
I didn't write much code in this but it seems decently formatted.

**Comment by Trueffeloot** [comment]
Sorry my bad, with the references I meant the forward and external reference comments which are empty now at the top of the TU. Forgot to say comments

**Review by TakaRikka — APPROVED** [review]

**Pull request merged**
